/* Generated By:JavaCC: Do not edit this line. SimpleGrParserTreeConstants.java Version 6.0_beta */
package de.dekarlab.simplegr.parser;

public interface SimpleGrParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTBOOLOREXPR = 1;
  public int JJTBOOLANDEXPR = 2;
  public int JJTBOOLEQUALSEXPR = 3;
  public int JJTBOOLNOTEQUALSEXPR = 4;
  public int JJTBOOLLESSTHANEXPR = 5;
  public int JJTBOOLGREATERTHANEXPR = 6;
  public int JJTBOOLLESSTHANOREQUALSEXPR = 7;
  public int JJTBOOLGREATERTHANOREQUALSEXPR = 8;
  public int JJTNUMADDEXPR = 9;
  public int JJTNUMSUBSTREXPR = 10;
  public int JJTNUMMULEXPR = 11;
  public int JJTNUMDIVEXPR = 12;
  public int JJTBOOLNOTEXPR = 13;
  public int JJTVARIABLE = 14;
  public int JJTFUNCEXPR = 15;
  public int JJTNUMBERLITERAL = 16;
  public int JJTBOOLEANLITERAL = 17;
  public int JJTSTRINGLITERAL = 18;
  public int JJTNULLEXPR = 19;


  public String[] jjtNodeName = {
    "void",
    "BoolOrExpr",
    "BoolAndExpr",
    "BoolEqualsExpr",
    "BoolNotEqualsExpr",
    "BoolLessThanExpr",
    "BoolGreaterThanExpr",
    "BoolLessThanOrEqualsExpr",
    "BoolGreaterThanOrEqualsExpr",
    "NumAddExpr",
    "NumSubstrExpr",
    "NumMulExpr",
    "NumDivExpr",
    "BoolNotExpr",
    "Variable",
    "FuncExpr",
    "NumberLiteral",
    "BooleanLiteral",
    "StringLiteral",
    "NullExpr",
  };
}
/* JavaCC - OriginalChecksum=3cf4f389f1cbb08139845ae8e735d73b (do not edit this line) */
