/* Generated By:JJTree&JavaCC: Do not edit this line. SimpleGrParserConstants.java */
package de.dekarlab.simplegr.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleGrParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NumberLit = 6;
  /** RegularExpression Id. */
  int BooleanLit = 7;
  /** RegularExpression Id. */
  int StringLit = 8;
  /** RegularExpression Id. */
  int Null = 9;
  /** RegularExpression Id. */
  int And = 10;
  /** RegularExpression Id. */
  int Or = 11;
  /** RegularExpression Id. */
  int Not = 12;
  /** RegularExpression Id. */
  int Identifier = 13;
  /** RegularExpression Id. */
  int Equal = 14;
  /** RegularExpression Id. */
  int NotEqual = 15;
  /** RegularExpression Id. */
  int LessThan = 16;
  /** RegularExpression Id. */
  int LessEqualThan = 17;
  /** RegularExpression Id. */
  int GreaterThan = 18;
  /** RegularExpression Id. */
  int GreaterEqualThan = 19;
  /** RegularExpression Id. */
  int Plus = 20;
  /** RegularExpression Id. */
  int Minus = 21;
  /** RegularExpression Id. */
  int Div = 22;
  /** RegularExpression Id. */
  int Mult = 23;
  /** RegularExpression Id. */
  int Open = 24;
  /** RegularExpression Id. */
  int Close = 25;
  /** RegularExpression Id. */
  int Comma = 26;
  /** RegularExpression Id. */
  int Letter = 27;
  /** RegularExpression Id. */
  int Digit = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<NumberLit>",
    "<BooleanLit>",
    "<StringLit>",
    "\"NULL\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<Identifier>",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<Letter>",
    "<Digit>",
  };

}
